import * as Marketplace from './marketplace';
import * as Order from './order';
import * as Orders from './orders';
import * as History from './history';
import * as Balance from './balance';

export const marketplace = Marketplace.marketplace;
export const orderPending = Order.pending;
export const orderPartial40 = Order.partial40;
export const orderPartial80 = Order.partial80;
export const orderCompleted = Order.completed;
export const orderCancelled = Order.cancelled;
export const orderCancelled40 = Order.cancelled40;
export const orders = Orders.orders;
export const ordersEmpty = Orders.empty;
export const historyCompleted = History.completed;
export const historyCancelled = History.cancelled;
export const historyPending = History.pending;
export const historyPartialCancelled = History.partialCancelled;
export const historyPartialProgress = History.partialProgress;
export const historyPartialCompleted = History.partialCompleted;
export const fullBalance = Balance.full;
export const emptyBalance = Balance.empty;